In [4]:
import tensorflow as tf

In [5]:
#load and prepare dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.25582415,  0.83408326, -0.07177931, -0.06183019, -0.18195754,
         0.02279082, -0.7070976 , -0.2493732 , -0.63880825,  0.4423206 ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07620063, 0.22662057, 0.09159847, 0.09251434, 0.08204241,
        0.10068378, 0.04852583, 0.07669378, 0.05195539, 0.1531648 ]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.2957706

In [11]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2931 - accuracy: 0.9149
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1427 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1080 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0868 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0766 - accuracy: 0.9759


In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0735 - accuracy: 0.9768


[0.07351724803447723, 0.9768000245094299]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.2164338e-08, 3.3804926e-10, 8.7867181e-07, 6.1107683e-05,
        5.4268509e-13, 3.0386014e-09, 5.2171397e-13, 9.9993646e-01,
        3.5333142e-07, 1.1293791e-06],
       [1.3204481e-09, 3.4246848e-05, 9.9993384e-01, 2.7124914e-05,
        2.8849922e-17, 2.8977422e-06, 4.2557322e-09, 7.0379129e-15,
        1.9544264e-06, 4.2791838e-12],
       [1.9675552e-07, 9.9956840e-01, 1.2436773e-05, 4.2684883e-06,
        7.7571322e-06, 6.1627229e-06, 4.9480777e-06, 2.8334348e-04,
        1.1123873e-04, 1.0859961e-06],
       [9.9907541e-01, 7.5529783e-08, 6.7858437e-06, 8.0899167e-07,
        3.3973287e-05, 2.4504954e-05, 8.2999340e-04, 1.9230269e-05,
        3.3845967e-07, 8.8529077e-06],
       [2.3587523e-07, 8.7841479e-10, 7.6784033e-07, 4.5359577e-08,
        9.9345946e-01, 1.0014463e-07, 1.1387015e-06, 4.6851677e-05,
        1.6098685e-06, 6.4897784e-03]], dtype=float32)>