In [1]:
import tensorflow as tf

In [2]:
#load and prepare dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.4330154 ,  0.6847238 , -0.01127092,  0.00772351,  0.06851726,
        -0.27247083,  0.84099317,  0.5878074 ,  0.1888707 ,  0.20736253]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.11083951, 0.1425641 , 0.07107936, 0.07244238, 0.07698304,
        0.05474013, 0.16667755, 0.12939572, 0.08682883, 0.08844938]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.905158

In [8]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3007 - accuracy: 0.9123
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1449 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1091 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0900 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0763 - accuracy: 0.9758


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0765 - accuracy: 0.9784


[0.07654716074466705, 0.9783999919891357]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.16893079e-07, 2.86450974e-09, 5.24403163e-07, 1.42418958e-05,
        1.14486823e-11, 1.79111723e-07, 1.88647261e-13, 9.99980211e-01,
        7.23889286e-08, 4.42271403e-06],
       [7.63492647e-09, 7.84938893e-05, 9.99916196e-01, 3.38807672e-06,
        4.62588979e-17, 9.95620780e-07, 4.83613753e-08, 6.24639619e-15,
        9.97677603e-07, 6.34488325e-15],
       [1.10712172e-07, 9.99340832e-01, 2.86903287e-05, 5.58285456e-06,
        1.43548808e-04, 2.15948580e-06, 8.32412661e-06, 4.00755991e-04,
        6.49776266e-05, 4.94561118e-06],
       [9.99980330e-01, 2.73550960e-09, 9.04678473e-07, 1.31244482e-08,
        7.43439310e-10, 3.02374178e-06, 1.02231015e-05, 5.41603322e-06,
        9.53608637e-10, 1.09702647e-07],
       [1.74836111e-06, 1.55740185e-10, 1.10912310e-07, 5.16837684e-09,
        9.98967171e-01, 7.58695137e-07, 6.62392836e-07, 3.50098671e-05,
        3.83331198e-08, 9.94529226e-04]], dtype=float32)>